### ISSUE TITLE
Incompatible with latest pubsub client

### ISSUE THREAD

**Issue by yanickbelanger** [knarz/pubsub-emulator#1]
The latest version of the pubsub client (in golang, and probably other languages) are now incompatible with the version of your pubsub emulator available on dockerhub. The latest client uses gRPC streaming exclusively (the version before had a fallback to HTTP long-poll) for the receive function, and your current docker image has an older version of the emulator that does not offer gRPC endpoints.

I've tested with the latest version of the emulator and it now supports gRPC. Could you please update the image on dockerhub with the latest version of the emulator? Thank you.

**Comment by knarz** [comment]
Hey, thank you for the report. I just triggered a new build. Let me know if that fixed it.

**Comment by yanickbelanger** [comment]
It works great now, thank you for the quick update!
